[project]
name = "obsidian-notes-to-anki"
version = "0.1.0"
description = "Obsidian note cleaner for ANKI"
readme = "README.md"
authors = [
    { name = "Lucas", email = "virgillitolucas430@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
]

[project.scripts]
obsidian-notes-to-anki = "obsidian_notes_to_anki.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]
